### ISSUE TITLE
What's the status of that project?

### ISSUE THREAD

**Issue by wdembinski** [jefflongo/stm32nes#4]
Hey @jefflongo 
Is your project working properly? Have you tried to run it on PC or some MCU. I'm interested in creating NES console based on STM32 and currently looking what needs to be done to achieve this. I saw several working projects - most of them doesn't have very detailed README files. Can you help on this, what steps I need to do to make such console? Maybe you have some drafts descriptions and could share them?

**Comment by jefflongo** [comment]
Hello there. I started this project for a class I was taking in college. I didn't end up finishing. At the time, the current state of the project was I had used FATFS to load a ROM off an SD card to run on the emulated system, and had a working parallel display driver. The PPU was largely incomplete and not working, and there was no frame limiter. Also mapper0 was the only implemented mapper.

I at one point decided to refactor the project (my coding skills were not as great at the original time of writing, and the project was time-constrained) to run on PC first in a platform-independent implementation, with abstractions on the ROM loading layer and frame buffer output layer, such that I could easily swap out displaying via something like SDL2 or a parallel display driver. The idea being to make it easier to test/debug without worrying about the STM32 specific stuff.

I have since abandoned this project as I do not have as much free time to work on it anymore. The current state of the codebase is bulletproof CPU emulator, but not much else. Feel free to take from this project what you will.

If I were to continue this project, I would probably take the following steps:
- Create a C-based platform-independent NES emulator with abstractions around the hardware peripherals (display, audio, controller, file loading)
- On the STM32, implement the hardware peripherals (display driver for display, controller is just SPI) and test them
- Connect your hardware peripherals implementations to the emulator

Hope this helps.
